# YAML Config File for BERT Finetuned Models

do_train: True

do_eval : True

sup_train_data_dir: './Data/proc_data/GoT/train_12000'

eval_data_dir:  './Data/proc_data/GoT/dev'

bert_config_file:  './bert_pretrained/bert_base/bert_config.json'

vocab_file:  './bert_pretrained/bert_base/vocab.txt'

init_checkpoint:  './bert_pretrained/bert_base/bert_model.ckpt'

task_name:  'GoT'

model_dir:  'model/lr4_12000' 

num_train_steps:  3000 

learning_rate:  0.00004

num_warmup_steps:  300 